name = "chronosina-media"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "chronosina-audio"

[vars]
FRONTEND_URL = "https://chronosina.pages.dev"
