name = "chronosina-payment"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "chronosina-db"
database_id = "cfcfe128-01ac-43c6-8df8-d9ba8328f1a7"

[vars]
FRONTEND_URL = "https://loonglore.com"
JWT_ISSUER = "chronosina"
CREEM_API_BASE = "https://api.creem.io"
CREEM_PRODUCT_MONTHLY = "prod_69Xy8rCrJhw84CSDCNWoq0"
CREEM_PRODUCT_YEARLY = "prod_42NkjUt0LGhuuN1m8Rrekv"
