name = "chronosina-auth"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "chronosina-db"
database_id = "cfcfe128-01ac-43c6-8df8-d9ba8328f1a7"

[vars]
FRONTEND_URL = "https://gouhongshen-gmail.github.io/article.github.io"
JWT_ISSUER = "chronosina"
GOOGLE_CLIENT_ID = "182609735993-2jekrkb2dg02j25f4ion4vu11sjdk9sb.apps.googleusercontent.com"
X_CLIENT_ID = "bW0zNDJUVHV2d2RSZmJFSWI4dlE6MTpjaQ"
RESEND_FROM_EMAIL = "ChronoSina <no-reply@example.com>"
